services:
  hub-story:
    container_name: hub-story
    build:
      context: ./
      dockerfile: DOCKERFILE
    ports:
      - "${API_PORT:-5000}:5000"
    environment:
      - FAL_KEY=${FAL_KEY}
      - IMAGE_WIDTH=${IMAGE_WIDTH:-600}
      - IMAGE_HEIGHT=${IMAGE_HEIGHT:-600}
      - DIFFUSION_STEPS=${DIFFUSION_STEPS:-4}
      - DEFAULT_SCENE_COUNT=${DEFAULT_SCENE_COUNT:-5}
      - API_PORT=${API_PORT:-5000}
      - STORIES_DIR=/app/stories
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./dreamteller.db}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./stories:/app/stories
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  stories:
    driver: local